apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment-on-efs
  labels:
    app: httpd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: fontend-httpd
        image: httpd
        volumeMounts:
        - name: efs-httpd-pv
          mountPath: /usr/local/apache2/htdocs/
        ports:
        - containerPort: 80
      volumes:
      - name: efs-httpd-pv
        persistentVolumeClaim:
          claimName: efs-httpd-claim