apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-on-nsf
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: ngnix-fn
        image: nginx
        volumeMounts:
        - name: pv-nsf-nginx
          mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
      volumes:
      - name: pv-nsf-nginx
        persistentVolumeClaim:
          claimName: nfs-nginx-claim