apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nsf-nginx
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/diskf/k8s-data/nginxdata
    server: 10.202.3.200
    readOnly: false

    