apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-nfs-pv 
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/nsf-mount-data/mysql8data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-nfs-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30007
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-test-dev
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata: 
      labels: 
        app: mysql
    spec:
      volumes:
        - name: mysql-nfs-pv
          PersistentVolumeClaim:
            claimName: mysql-nfs-pv-claim
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: mysql-root-pass
                  key:  password
            - name: MYSQL_DATABASE
              valueFrom: 
                secretKeyRef:
                  name: mysql-db-url
                  key: database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-user-pass
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-user-pass
                  key: password
          volumeMounts:
            - name: mysql-nfs-pv
              mountPath: /var/lib/mysql
          ports:
            - containerPort: 3306
              name: mysql